import { SxProps } from '@mui/material';

export const styles = {
    container: {
        position: "relative",
        textAlign: "center",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        height: "100vh",
    },
    muteButton: {
        position: "absolute",
        top: "16px",
        left: "16px",
        color: "white",
    },
    logo: {
        pb: '30px',
        width: '50vh', // GameScreen specific
        height: 'auto', // GameScreen specific
    },
    startButton: {
        width: "15%",
        height: "8%",
        borderRadius: "100px",
        border: "5px solid #e87431",
        fontSize: "28px",
        fontWeight: "800",
        background: "linear-gradient(180deg, #51bae0 20%, #5181e0 90%)",
        color: "white",
    },
    resetButton: {
        width: "30%",
        height: "100%",
        fontSize: "18px",
        fontWeight: "800",
        borderRadius: "100px",
        border: "5px solid #e87431",
        background: "linear-gradient(180deg, #51bae0 20%, #5181e0 90%)",
        color: "white",
    },
    matchHistoryTitle: {
        paddingY: "20px",
        color: "whitesmoke",
        fontSize: '20px',
        fontWeight: '600',
    },
    marqueeContainer: {
        overflow: 'hidden',
        height: '200px',
        width: '100%',
        position: 'relative',
        '&::before': {
            content: '""',
            position: 'absolute',
            zIndex: 2,
            top: 0,
            left: 0,
            width: '100%',
            height: '40px',
            background: 'linear-gradient(to bottom, #34b4eb, transparent)',
            pointerEvents: 'none',
        },
        '&::after': {
            content: '""',
            position: 'absolute',
            bottom: 0,
            left: 0,
            width: '100%',
            height: '20px',
            background: 'linear-gradient(to top, #34b4eb, transparent)',
            pointerEvents: 'none',
        },
    },
    list: {
        display: 'flex',
        flexDirection: 'column',
        paddingY: "0",
        animation: `slide 15s infinite linear`,
        '@keyframes slide': {
            from: { transform: 'translateY(0%)' },
            to: { transform: 'translateY(-100%)' },
        },
    },
    modalContainer: {
        width: 400,
        color: "transparent",
        overflow: "hidden",
        borderRadius: 10,
        p: 4,
    },
    closeIcon: {
        position: 'absolute',
        top: 8,
        right: 8,
        color: "#e87431",
    },
    playerText: {
        color: "whitesmoke",
        fontSize: '20px',
        fontWeight: '600',
        textAlign: "start",
        px: "10px",
        pt: "10px"
    },
    textField: {
        backgroundColor: "#ebf5ff",
        borderRadius: "20px",
        '& .MuiOutlinedInput-root': {
            borderRadius: '20px',
            '& fieldset': {
                border: "2px solid #e87431",
            },
            '&:hover fieldset': {
                border: "2px solid #e87431",
            },
            '&.Mui-focused fieldset': {
                border: "2px solid #e87431",
            },
        },
    },
    errorText: {
        color: "#b02e2e",
        fontSize: '16px',
        fontWeight: '600',
        textAlign: "center",
        px: "10px",
        pt: "20px",
    },
    continueButtonContainer: {
        paddingX: "50px",
        paddingTop: "20px",
    },
    continueButton: {
        width: "100%",
        height: "5%",
        borderRadius: "100px",
        border: "5px solid #e87431",
        fontSize: "28px",
        fontWeight: "800",
        background: "linear-gradient(180deg, #51bae0 20%, #5181e0 90%)",
        color: "white",
        alignSelf: "center",
    },
    gameCell: {
        height: "17vh",
        width: "97%",
        backgroundColor: "#d7d9a9",
        fontSize: "120px",
        fontFamily: "cursive",
        margin: "5px",
    },
    playerX: {
        color: "#ed4c4c",
        fontFamily: "cursive",
        paddingLeft: "15px",
        fontSize: "60px",
    },
    playerO: {
        color: "#2c47a8",
        fontFamily: "cursive",
        paddingRight: "15px",
        fontSize: "60px",
    },
    gameBoard: {
        width: "30%",
        backgroundColor: "#5181e0",
        borderRadius: "10px",
    },
    buttonContainer: {
        display: "flex",
        flexDirection: "row",
        width: "30%",
        justifyContent: "space-evenly",
        paddingTop: "20px",
    },
};
